### PR TITLE
Fix tenant constraint in campaign stats #314

### PR DESCRIPTION
**Pull request by celber**

### CODE REVIEW

**Comment by celber** [comment]
@nczeranka yes it is bad idea but 1) it is not that much data 2) see comment on :212, it was done on db side before but it did not work. Looks like our relations are wrong but I took recommended aproach: first get it work, then optimalize. We can create subtask to see why it didn't work on db side but this here is functional and can be used already

**Comment by nczeranka** [comment]
As far as I know did the db approach did work, except of the customer restriction. Adding a customer restriction should be fairly easy.
Concerning "not much data": this is wrong. Deka, our first customer will have on start already 3000 suppliers. And it will grow.
So please improve query to fullfil customer restriction.

**Comment by celber** [comment]
as long as restriction does not work you cant query campaignconctacts and include its campaign. You need to go other way and query campaigns and include its contacts. But there is second issue. For unknown reason only one contact is incluided, not all
so next query needs to be done to filter it manually

**Comment by nczeranka** [comment]
The old SQL query in fact did five independent queries. I guess your problem was that the QueryGenerator does not allow to add an include (to join to Contact and filter on customerId). (And what is the CampaignId in the resultset for?)
Please provide details "why it does not work" in future.

I agree that a simply adjustment of the query does not work (see comment above), but the query itself does not make much sense this way, either.

Please adjust the query in either
- one query with grouping on status plus summing the different status locally. i.e.
`select CampaignContact.status, count(*)
  from CampaignContact
    join Campaign on Campaign.id = CampaignContact.campaignId
  where Campaign.customerId = 'ncc'
group by status;`
- single execution of the the four distinct queries (that are used already anyway) but with filtering on the customerId.

**Pull request merged**
