### PR TITLE
session timeout for ajax calls - workaround

### PR DESCRIPTION
**Pull request by theflexbird**
#79

### CODE REVIEW

**Comment by kwierchris** [comment]
Please let suspend this for a while. May be we can find a way to do this more globally and more implicit. Currently I do not think that it would be a good idea to inject this middleware manually by the developer on every request that has to be made. We should at least try to find a more central solution for that.

**Comment by theflexbird** [comment]
It would be good to return 401 instead of redirecting for all ajax calls (endpoints where url is starting with `/api/`). What do you thing @kwierchris ?

**Comment by kwierchris** [comment]
We have services that do not prepend /api to their endpoints. @sureshvarman-cronj and I are trying to find a solution.

**Comment by nczeranka** [comment]
Postponed

**Comment by nczeranka** [comment]
New approach of Chris is available in branch feature/template-selection

**Pull request closed without merging**
